spring:
  application:
    name: deeepsleep-student-management-backend

  datasource:
    url: jdbc:mysql://202.194.14.120:3306/java_3_35
    username: java_3_35
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtpdm.aliyun.com
    port: 465
    username: noreply@mail.sentiexception.com
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 15MB
  thymeleaf:
    prefix: classpath:/mail/

# MyBatis 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.deepsleep.data.po
  configuration:
    map-underscore-to-camel-case: true

# DeepSeek API配置
dssm:
  ai:
    key: ${DEEPSEEK_API_KEY}
    url: https://api.deepseek.com/v1/chat/completions
    model: deepseek-chat
    max-tokens: 4096

  code:
    interval-lock-expire-seconds: 60
    code-expire-seconds: 300
    max-fail-number: 5
    target-hash-secret: ${EMAIL_HASH_SECRET}

  email:
    from: ${spring.mail.username}

#jwt
jwt:
  secret: deeepsleep2026studentmanagementbackendsecretkey
  expiration-seconds: 3600

server:
  port: 22224

aliyun:
  oss:
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    region: cn-hongkong
    endpoint: http://dssm.sentiexception.com
    bucket: deepsleep-student-management-oss
    presigned-url-expire-seconds: 3600

  sms:
    access-key-id: ${SMS_ACCESS_KEY_ID}
    access-key-secret: ${SMS_ACCESS_KEY_SECRET}
    endpoint: dypnsapi.aliyuncs.com
    sign-name: 速通互联验证码
    template-code: 100001
